### ISSUE TITLE
sorry but i can only contact you here, about the hexo-theme-pln

### ISSUE THREAD

**Issue by gaoryrt** [aloisdg/aloisdg.github.io#1]
I am the writer of the hexo-theme-pln, i am happy to notice that you are using it right now. 

But I found that the Internationalization of this theme is not good enough: there're Chinese at the end of your article. 

I fixed it immediately and I hope you to git-pull the hexo-theme-pln repo to avoid the Chinese display bug.

Issues are always welcomed and I'd like to help.

**Comment by aloisdg** [comment]
I thought the problem was from my side. Thank you very much for this theme and for your implication! If I find any problem in your theme I will open an issue or a pr.

**Comment by aloisdg** [comment]
I am looking your i18n update. That very nice!

Also if you need a french translation, I can provide it.

**Comment by gaoryrt** [comment]
Thank you for your work on this repo. 

I will be very happy if you could give a help at french translation job.

Thanks.
